import { Player, PlayerRole, PlayerNationality } from "@/types/game";

function p(
  id: string,
  name: string,
  role: PlayerRole,
  nationality: PlayerNationality,
  basePrice: number,
  battingRating: number,
  bowlingRating: number,
  wicketkeeperRating = 0
): Player {
  return {
    id,
    name,
    role,
    nationality,
    basePrice,
    battingRating,
    bowlingRating,
    wicketkeeperRating,
    currentForm: 0,
    injured: false,
    injuredForMatches: 0,
    soldTo: null,
    soldPrice: null,
  };
}

// Base price tiers (in cr):
// 2.0  → Marquee superstars
// 1.5  → Stars
// 1.0  → Good capped players
// 0.5  → Fringe capped / decent uncapped
// 0.2  → Raw uncapped / domestic talent

export const PLAYER_POOL: Player[] = [

  // ── MARQUEE INDIAN SUPERSTARS ──────────────────────────
  p("rohit",        "Rohit Sharma",           "batsman",      "India",        2,   93, 10),
  p("virat",        "Virat Kohli",            "batsman",      "India",        2,   95, 10),
  p("hardik",       "Hardik Pandya",          "allrounder",   "India",        2,   80, 82),
  p("bumrah",       "Jasprit Bumrah",         "bowler",       "India",        2,   20, 97),
  p("klrahul",      "KL Rahul",               "wicketkeeper", "India",        2,   88, 10, 90),
  p("pant",         "Rishabh Pant",           "wicketkeeper", "India",        2,   88, 15, 92),
  p("shreyas",      "Shreyas Iyer",           "batsman",      "India",        2,   85, 10),
  p("surya",        "Suryakumar Yadav",       "batsman",      "India",        2,   91, 10),
  p("jadeja",       "Ravindra Jadeja",        "allrounder",   "India",        2,   75, 84),
  p("shubman",      "Shubman Gill",           "batsman",      "India",        1.5, 89, 10),
  p("yashasvi",     "Yashasvi Jaiswal",       "batsman",      "India",        1.5, 86, 10),
  p("ruturaj",      "Ruturaj Gaikwad",        "batsman",      "India",        1,   84, 10),
  p("sanju",        "Sanju Samson",           "wicketkeeper", "India",        2,   83, 10, 86),
  p("ishan",        "Ishan Kishan",           "wicketkeeper", "India",        1,   82, 10, 85),
  p("axar",         "Axar Patel",             "allrounder",   "India",        1,   72, 80),
  p("kuldeep",      "Kuldeep Yadav",          "bowler",       "India",        1,   22, 85),
  p("siraj",        "Mohammed Siraj",         "bowler",       "India",        1,   15, 88),
  p("arshdeep",     "Arshdeep Singh",         "bowler",       "India",        1,   20, 82),
  p("bhuvi",        "Bhuvneshwar Kumar",      "allrounder",   "India",        1,   35, 80),
  p("shardul",      "Shardul Thakur",         "allrounder",   "India",        1,   52, 78),

  // ── MARQUEE OVERSEAS STARS ─────────────────────────────
  p("cummins",      "Pat Cummins",            "allrounder",   "Australia",    2,   55, 91),
  p("starc",        "Mitchell Starc",         "bowler",       "Australia",    2,   30, 90),
  p("head",         "Travis Head",            "batsman",      "Australia",    2,   87, 35),
  p("warner",       "David Warner",           "batsman",      "Australia",    1.5, 88, 10),
  p("smith",        "Steve Smith",            "batsman",      "Australia",    1.5, 86, 30),
  p("maxwell",      "Glenn Maxwell",          "allrounder",   "Australia",    1.5, 85, 72),
  p("green",        "Cameron Green",          "allrounder",   "Australia",    1,   76, 75),
  p("stokes",       "Ben Stokes",             "allrounder",   "England",      1.5, 82, 86),
  p("curran",       "Sam Curran",             "allrounder",   "England",      1.5, 70, 80),
  p("buttler",      "Jos Buttler",            "wicketkeeper", "England",      2,   91, 10, 92),
  p("livingstone",  "Liam Livingstone",       "allrounder",   "England",      1,   80, 72),
  p("brook",        "Harry Brook",            "batsman",      "England",      1.5, 88, 20),
  p("salt",         "Phil Salt",              "wicketkeeper", "England",      1,   80, 10, 83),
  p("bairstow",     "Jonny Bairstow",         "wicketkeeper", "England",      1,   84, 10, 86),
  p("pooran",       "Nicholas Pooran",        "wicketkeeper", "West Indies",  1.5, 85, 10, 87),
  p("conway",       "Devon Conway",           "wicketkeeper", "New Zealand",  1,   83, 10, 84),
  p("dekock",       "Quinton de Kock",        "wicketkeeper", "South Africa", 1.5, 86, 10, 88),
  p("williamson",   "Kane Williamson",        "batsman",      "New Zealand",  1.5, 88, 20),
  p("rashid",       "Rashid Khan",            "allrounder",   "Afghanistan",  2,   65, 94),
  p("boult",        "Trent Boult",            "bowler",       "New Zealand",  1.5, 22, 90),

  // ── TOP ALL-ROUNDERS ───────────────────────────────────
  p("russell",      "Andre Russell",          "allrounder",   "West Indies",  2,   86, 84),
  p("stoinis",      "Marcus Stoinis",         "allrounder",   "Australia",    1,   78, 74),
  p("holder",       "Jason Holder",           "allrounder",   "West Indies",  1,   62, 83),
  p("moeen",        "Moeen Ali",              "allrounder",   "England",      1,   72, 76),
  p("marsh",        "Mitchell Marsh",         "allrounder",   "Australia",    1.5, 80, 76),
  p("daryl",        "Daryl Mitchell",         "allrounder",   "New Zealand",  1,   78, 65),
  p("shivam_d",     "Shivam Dube",            "allrounder",   "India",        1,   70, 58),
  p("vijay_s",      "Vijay Shankar",          "allrounder",   "India",        0.5, 65, 65),
  p("deepak_h",     "Deepak Hooda",           "allrounder",   "India",        0.5, 68, 55),
  p("washington",   "Washington Sundar",      "allrounder",   "India",        1,   68, 75),
  p("ashwin",       "Ravichandran Ashwin",    "allrounder",   "India",        1,   65, 86),
  p("omarzai",      "Azmatullah Omarzai",     "allrounder",   "Afghanistan",  0.5, 65, 68),
  p("janat",        "Karim Janat",            "allrounder",   "Afghanistan",  0.5, 60, 65),
  p("shepherd",     "Romario Shepherd",       "allrounder",   "West Indies",  0.5, 62, 72),
  p("timdavid",     "Tim David",              "batsman",      "Singapore",    1,   82, 10),
  p("narine",       "Sunil Narine",           "allrounder",   "West Indies",  2,   78, 88),
  p("rachin",       "Rachin Ravindra",        "allrounder",   "New Zealand",  1,   80, 68),
  p("venkatesh",    "Venkatesh Iyer",         "allrounder",   "India",        1,   74, 65),
  p("bcarse",       "Brydon Carse",           "allrounder",   "England",      0.5, 45, 72),
  p("woakes",       "Chris Woakes",           "allrounder",   "England",      1,   58, 78),
  p("sraza",        "Sikandar Raza",          "allrounder",   "Zimbabwe",     0.5, 65, 68),
  p("dsams",        "Daniel Sams",            "allrounder",   "Australia",    0.5, 58, 68),
  p("aagar",        "Ashton Agar",            "allrounder",   "Australia",    0.5, 52, 70),
  p("orobinson",    "Ollie Robinson",         "allrounder",   "England",      0.5, 35, 76),
  p("joverton",     "Jamie Overton",          "allrounder",   "England",      0.2, 42, 66),
  p("coverton",     "Craig Overton",          "allrounder",   "England",      0.2, 40, 65),
  p("osmith",       "Odean Smith",            "allrounder",   "West Indies",  0.5, 55, 72),
  p("drakes",       "Dominic Drakes",         "allrounder",   "West Indies",  0.2, 52, 65),
  p("rutherford",   "Sherfane Rutherford",    "allrounder",   "West Indies",  0.5, 68, 58),
  p("mayers",       "Kyle Mayers",            "allrounder",   "West Indies",  0.5, 72, 62),
  p("campher",      "Curtis Campher",         "allrounder",   "Ireland",      0.2, 58, 62),
  p("lwood",        "Luke Wood",              "allrounder",   "England",      0.2, 40, 68),

  // ── TOP BOWLERS ────────────────────────────────────────
  p("rabada",       "Kagiso Rabada",          "bowler",       "South Africa", 2,   25, 93),
  p("nortje",       "Anrich Nortje",          "bowler",       "South Africa", 1,   18, 88),
  p("hazlewood",    "Josh Hazlewood",         "bowler",       "Australia",    1.5, 15, 88),
  p("lockie",       "Lockie Ferguson",        "bowler",       "New Zealand",  1,   18, 86),
  p("ngidi",        "Lungi Ngidi",            "bowler",       "South Africa", 1,   15, 84),
  p("noor",         "Noor Ahmad",             "bowler",       "Afghanistan",  1,   15, 83),
  p("zadran",       "Fazalhaq Farooqi",       "bowler",       "Afghanistan",  0.5, 15, 80),
  p("natarajan",    "T Natarajan",            "bowler",       "India",        0.5, 14, 76),
  p("khaleel",      "Khaleel Ahmed",          "bowler",       "India",        0.5, 14, 74),
  p("avesh",        "Avesh Khan",             "bowler",       "India",        0.5, 15, 79),
  p("mukesh_k",     "Mukesh Kumar",           "bowler",       "India",        1,   12, 73),
  p("mohit_s",      "Mohit Sharma",           "bowler",       "India",        0.5, 15, 75),
  p("unadkat",      "Jaydev Unadkat",         "bowler",       "India",        0.5, 18, 75),
  p("prasidh",      "Prasidh Krishna",        "bowler",       "India",        1,   18, 80),
  p("kuldeep_s",    "Kuldeep Sen",            "bowler",       "India",        0.5, 12, 74),
  p("akash_deep",   "Akash Deep",             "bowler",       "India",        1,   14, 76),
  p("ravi_b",       "Ravi Bishnoi",           "bowler",       "India",        1,   18, 80),
  p("mayank_y",     "Mayank Yadav",           "bowler",       "India",        1,   14, 76),
  p("joseph_a",     "Alzarri Joseph",         "bowler",       "West Indies",  1,   20, 85),
  p("naveen",       "Naveen-ul-Haq",          "bowler",       "Afghanistan",  0.5, 14, 78),
  p("mustafiz",     "Mustafizur Rahman",      "bowler",       "Bangladesh",   0.5, 12, 80),
  p("coetzee",      "Gerald Coetzee",         "bowler",       "South Africa", 0.5, 15, 80),
  p("spencer",      "Spencer Johnson",        "bowler",       "Australia",    0.5, 14, 78),
  p("jlittle",      "Josh Little",            "bowler",       "Ireland",      0.5, 12, 76),
  p("madushanka",   "Dilshan Madushanka",     "bowler",       "Sri Lanka",    0.5, 12, 78),
  p("atkinson",     "Gus Atkinson",           "allrounder",   "England",      1,   45, 80),
  p("akash_s",      "Akash Singh",            "bowler",       "India",        0.2, 10, 66),
  p("shamar",       "Shamar Joseph",          "bowler",       "West Indies",  0.5, 15, 78),
  p("shamsi",       "Tabraiz Shamsi",         "bowler",       "South Africa", 0.5, 12, 78),
  p("maharaj",      "Keshav Maharaj",         "bowler",       "South Africa", 0.5, 20, 76),
  p("sabbott",      "Sean Abbott",            "bowler",       "Australia",    0.5, 14, 76),
  p("nellis",       "Nathan Ellis",           "bowler",       "Australia",    0.5, 12, 74),
  p("zampa",        "Adam Zampa",             "bowler",       "Australia",    0.5, 14, 78),
  p("adil",         "Adil Rashid",            "bowler",       "England",      0.5, 22, 78),
  p("topley",       "Reece Topley",           "bowler",       "England",      0.5, 12, 78),
  p("mwood",        "Mark Wood",              "bowler",       "England",      1,   20, 86),
  p("tmills",       "Tymal Mills",            "bowler",       "England",      0.5, 10, 76),
  p("bstanlake",    "Billy Stanlake",         "bowler",       "Australia",    0.2, 10, 72),
  p("rgleeson",     "Richard Gleeson",        "bowler",       "England",      0.2, 10, 68),
  p("mpotts",       "Matthew Potts",          "bowler",       "England",      0.2, 14, 66),
  p("mohsin_k",     "Mohsin Khan",            "bowler",       "India",        0.5, 12, 74),
  p("chetan",       "Chetan Sakariya",        "bowler",       "India",        0.5, 14, 74),
  p("sandeep",      "Sandeep Sharma",         "bowler",       "India",        0.5, 14, 74),
  p("yash_d",       "Yash Dayal",             "bowler",       "India",        1,   14, 73),
  p("kartik",       "Kartik Tyagi",           "bowler",       "India",        0.2, 12, 68),
  p("basil",        "Basil Thampi",           "bowler",       "India",        0.2, 12, 67),
  p("siddharth",    "M Siddharth",            "bowler",       "India",        0.2, 12, 66),
  p("varun",        "Varun Chakravarthy",     "bowler",       "India",        1,   18, 80),
  p("anshul",       "Anshul Kamboj",          "bowler",       "India",        0.2, 12, 68),
  p("gurjap",       "Gurjapneet Singh",       "bowler",       "India",        0.2, 10, 66),
  p("kamlesh",      "Kamlesh Nagarkoti",      "bowler",       "India",        0.2, 12, 68),
  p("digvesh",      "Digvesh Singh",          "bowler",       "India",        0.2, 10, 64),
  p("arshad_k",     "Arshad Khan",            "bowler",       "India",        0.2, 10, 65),
  p("gurnoor",      "Gurnoor Brar",           "bowler",       "India",        0.2, 12, 66),
  p("nissanka",     "Pathum Nissanka",         "batsman",      "Sri Lanka",    0.5, 78, 10),

  // ── WICKETKEEPERS ──────────────────────────────────────
  p("jitesh",       "Jitesh Sharma",          "wicketkeeper", "India",        1,   76, 10, 80),
  p("dhruv",        "Dhruv Jurel",            "wicketkeeper", "India",        0.5, 70, 10, 78),
  p("ks_bharat",    "KS Bharat",              "wicketkeeper", "India",        0.5, 65, 10, 74),
  p("anuj",         "Anuj Rawat",             "wicketkeeper", "India",        0.5, 62, 10, 70),
  p("abhish_p",     "Abhishek Porel",         "wicketkeeper", "India",        0.5, 60, 10, 68),
  p("stubbs",       "Tristan Stubbs",         "wicketkeeper", "South Africa", 0.5, 72, 10, 78),
  p("ferreira",     "Donovan Ferreira",       "wicketkeeper", "South Africa", 0.5, 65, 10, 72),
  p("gurbaz",       "Rahmanullah Gurbaz",     "wicketkeeper", "Afghanistan",  1,   78, 10, 82),
  p("klaasen",      "Heinrich Klaasen",       "wicketkeeper", "South Africa", 1.5, 87, 10, 88),
  p("carey",        "Alex Carey",             "wicketkeeper", "Australia",    0.5, 72, 10, 80),
  p("tbanton",      "Tom Banton",             "wicketkeeper", "England",      0.5, 72, 10, 75),
  p("sbillings",    "Sam Billings",           "wicketkeeper", "England",      0.5, 70, 10, 74),
  p("bmcdermott",   "Ben McDermott",          "wicketkeeper", "Australia",    0.5, 70, 10, 74),

  // ── YOUNG INDIAN TALENT ────────────────────────────────
  p("tilak",        "Tilak Varma",            "batsman",      "India",        1,   80, 20),
  p("abhishek_s",   "Abhishek Sharma",        "allrounder",   "India",        1,   74, 60),
  p("nehal",        "Nehal Wadhera",          "batsman",      "India",        0.5, 64, 15),
  p("rinku",        "Rinku Singh",            "batsman",      "India",        1,   78, 15),
  p("ayush_b",      "Ayush Badoni",           "batsman",      "India",        1,   72, 15),
  p("sameer",       "Sameer Rizvi",           "batsman",      "India",        0.5, 65, 10),
  p("aash_sh",      "Ashutosh Sharma",        "allrounder",   "India",        0.2, 60, 58),
  p("naman",        "Naman Dhir",             "allrounder",   "India",        0.5, 65, 55),
  p("angkrish",     "Angkrish Raghuvanshi",   "batsman",      "India",        0.5, 65, 10),
  p("rajvardhan",   "Rajvardhan Hangargekar", "allrounder",   "India",        0.2, 55, 62),
  p("arshin",       "Arshin Kulkarni",        "allrounder",   "India",        0.2, 58, 55),
  p("yuvraj_c",     "Yuvraj Chaudhary",       "bowler",       "India",        0.2, 12, 65),
  p("prince",       "Prince Yadav",           "bowler",       "India",        0.2, 10, 64),
  p("swastik",      "Swastik Chikara",        "batsman",      "India",        0.2, 58, 10),
  p("himmat",       "Himmat Singh",           "batsman",      "India",        0.2, 58, 10),
  p("abdul_s",      "Abdul Samad",            "allrounder",   "India",        0.5, 65, 52),

  // ── ADDITIONAL INTERNATIONAL BATSMEN ──────────────────
  p("faf",          "Faf du Plessis",         "batsman",      "South Africa", 1,   82, 10),
  p("miller",       "David Miller",           "batsman",      "South Africa", 1,   83, 10),
  p("phillips",     "Glenn Phillips",         "allrounder",   "New Zealand",  1,   78, 65),
  p("santner",      "Mitchell Santner",       "allrounder",   "New Zealand",  1,   65, 75),
  p("bevon",        "Bevon Jacobs",           "allrounder",   "West Indies",  0.2, 58, 55),
  p("breetzke",     "Matthew Breetzke",       "batsman",      "South Africa", 0.2, 60, 10),
  p("duckett",      "Ben Duckett",            "batsman",      "England",      0.5, 76, 10),
  p("bethell",      "Jacob Bethell",          "allrounder",   "England",      0.5, 68, 62),
  p("mousley",      "Dan Mousley",            "allrounder",   "England",      0.5, 62, 60),
  p("anderson",     "Jimmy Anderson",         "bowler",       "England",      0.5, 10, 78),
  p("jfm",          "Jake Fraser-McGurk",     "batsman",      "Australia",    1,   80, 10),
  p("tector",       "Harry Tector",           "batsman",      "Ireland",      0.2, 62, 20),
  p("bking",        "Brandon King",           "batsman",      "West Indies",  0.5, 75, 10),
  p("elewis",       "Evin Lewis",             "batsman",      "West Indies",  0.5, 76, 10),
  p("powell",       "Rovman Powell",          "batsman",      "West Indies",  0.5, 74, 10),
  p("cmunro",       "Colin Munro",            "batsman",      "New Zealand",  0.5, 74, 10),
  p("dmalan",       "Dawid Malan",            "batsman",      "England",      0.5, 74, 10),

  // ── INDIAN DOMESTIC ROLE PLAYERS ──────────────────────
  p("nitish",       "Nitish Rana",            "allrounder",   "India",        0.5, 72, 55),
  p("rahul_t",      "Rahul Tripathi",         "batsman",      "India",        0.5, 70, 10),
  p("deepak",       "Deepak Chahar",          "allrounder",   "India",        1,   45, 78),
  p("shahbaz",      "Shahbaz Ahmed",          "allrounder",   "India",        0.5, 62, 68),
  p("swapnil",      "Swapnil Singh",          "allrounder",   "India",        0.2, 52, 58),
];

// Shuffle for auction order
export function getAuctionOrder(): Player[] {
  const pool = [...PLAYER_POOL];
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool;
}

export function getPlayerById(id: string): Player | undefined {
  return PLAYER_POOL.find((p) => p.id === id);
}